kind: Service
apiVersion: v1
metadata:
  name:  router-service
  labels:
    name:  router-service
spec:
  selector:
    app:  router
  type:   ClusterIP 
  ports:
  - name:  http
    port:  80
    targetPort:  3000